site_name: NetData Documentation
repo_url: https://github.com/netdata/netdata
repo_name: GitHub
edit_uri: blob/htmldoc
site_description: NetData Documentation
copyright: NetData, 2018
docs_dir: src
site_dir: build
#use_directory_urls: false
theme:
    name: "material"
    custom_dir: themes/material
markdown_extensions:
 - extra
 - abbr
 - attr_list
 - def_list
 - fenced_code
 - footnotes
 - tables
 - admonition
 - codehilite
 - meta
 - nl2br
 - sane_lists
 - smarty
 - toc:
    permalink: True
    separator: "-"
 - wikilinks
nav:
- General:
    - 'index.md'
    - 'Introducing-netdata.md'
    - 'Why-netdata.md'
    - 'Performance-monitoring,-scaled-properly.md'
    - 'netdata-for-IoT.md'
    - 'Demo-Sites.md'
    - 'Other-monitoring-tools.md'
- Installation:
    - 'Installation.md'
    - 'Install-netdata-with-Static-Package.md'
    - 'netdata-package-maintainers.md'
    - 'Install-netdata-with-Docker.md'
    - 'Install-netdata-manually.md'
    - 'Install-netdata-on-other-systems.md'
    - 'Updating-Netdata.md'
    - 'Uninstall.md'
- Getting Started:
    - 'Getting-Started.md'
    - 'Command-Line-Options.md'
    - 'Log-Files.md'
    - 'Tracing-Options.md'
    - 'Performance.md'
    - 'Memory-Requirements.md'
    - 'netdata-security.md'
    - 'Netdata-Security-and-Disclosure-Information.md'
    - 'netdata-OOMScore.md'
    - 'netdata-process-priority.md'
- Configuration:
    - 'Configuration.md'
- Optimization:
    - 'high-performance-netdata.md'
    - 'Memory-Deduplication---Kernel-Same-Page-Merging---KSM.md'
    - 'netdata-virtual-memory-size.md'
- Database-Replication-and-Mirroring:
    - 'Replication-Overview.md'
    - 'Monitoring-ephemeral-nodes.md'
    - 'netdata-proxies.md'
- Backends-:
    - 'netdata-backends.md'
    - 'Using-Netdata-with-Prometheus.md'
    - 'Netdata,-Prometheus,-and-Grafana-Stack.md'
- Health-monitoring---Alarms:
    - 'health-monitoring.md'
    - 'health-configuration-reference.md'
    - 'health-configuration-examples.md'
    - Alarm Notifications:
        - 'health/notifications/README.md'
        - 'web-browser-notifications.md'
        - 'Alerta-monitoring-system.md'
        - 'discord-notifications.md'
        - 'email-notifications.md'
        - 'flock-notifications.md'
        - 'IRC-notifications.md'
        - 'kavenegar-notifications.md'
        - 'messagebird-notifications.md'
        - 'pagerduty-notifications.md'
        - 'pushbullet-notifications.md'
        - 'pushover-notifications.md'
        - 'RocketChat-notifications.md'
        - 'slack-notifications.md'
        - 'Syslog-Notifications.md'
        - 'telegram-notifications.md'
        - 'twilio-notifications.md'
        - 'Amazon-SNS-Notifications.md'
    - 'health-API-calls.md'
    - 'troubleshooting-alarms.md'
- Netdata-Registry:
    - 'mynetdata-menu-item.md'
- Netdata-Badges:
    - 'Generating-Badges.md'
- Data-Collection:
    - 'Add-more-charts-to-netdata.md'
    - 'Collectors-README.md'
    - Internal Plugins:
        - 'Internal-Plugins.md'
        - 'statsd.md'
        - 'monitoring-cgroups.md'
        - 'QoS.md'
        - 'monitoring-systemd-services.md'
        - 'Monitoring-disks.md'
    - External Plugins:
        - 'External-Plugins.md'
        - 'The-spectacles-of-a-web-server-log-file.md'
        - 'monitoring-IPMI.md'
        - Binary-Modules:
            - 'Apps-Plugin.md'
            - 'fping-Plugin.md'
        - Python-Modules:
            - 'Netdata-Python-Modules.md'
            - 'Monitoring-Go-Applications.md'
            - 'Monitoring-Java-Spring-Boot-Applications.md'
        - Nodejs-Modules:
            - 'General-Info-node.d.md'
        - BASH-Modules:
            - 'General-Info-charts.d.md'
        - Active-BASH-Modules:
            - 'ap.chart.sh.md'
            - 'apcupsd.chart.sh.md'
            - 'example.chart.sh.md'
            - 'charts.d.md'
            - 'opensips.chart.sh.md'
        - Obsolete-BASH-Modules:
            - 'Obsolete-BASH-Modules.md'
            - 'apache.chart.sh.md'
            - 'cpufreq.chart.sh.md'
            - 'mysql.chart.sh.md'
            - 'phpfpm.chart.sh.md'
            - 'tomcat.chart.sh.md'
    - Third Party Plugins:
        - 'Third-Party-Plugins.md'
- API-Documentation:
    - 'REST-API-v1.md'
    - 'receiving-netdata-metrics-from-shell-scripts.md'
- Web-Dashboards:
    - 'Overview.md'
    - 'Custom-Dashboards.md'
    - 'Custom-Dashboard-with-Confluence.md'
- Chart-Libraries:
    - 'Dygraph.md'
    - 'EasyPieChart.md'
    - 'Gauge.js.md'
    - 'jQuery-Sparkline.md'
    - 'Peity.md'
- Running-behind-another-web-server:
    - 'Running-behind-nginx.md'
    - 'Running-behind-apache.md'
    - 'Running-behind-lighttpd.md'
    - 'Running-behind-caddy.md'
- Contributing:
    - 'CONTRIBUTING.md'
    - 'CODE_OF_CONDUCT.md'
- Blog:
    - 'Donations-netdata-has-received.md'
    - 'a-github-star-is-important.md'
    - 'Release-Notes.md'
    - 'CPU-Usage.md'
    - 'DDOS.md'
